# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: Recife1985

# Variables to accompany `group_vars/development/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  kodefant.no:
    admin_password: Recife1985
    env:
      db_password: Recife1985
